name: Main Workflow

on:
  pull_request:
    branches:
      - release
    types: [opened, edited, closed]

jobs:
  check-pr-name:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is from dev to release
      id: check-branches
      run: |
        if [[ "${{ github.event.pull_request.base.ref }}" == "release" && "${{ github.event.pull_request.head.ref }}" == "dev" ]]; then
          echo "branches_matched=true" >> $GITHUB_ENV
        else
          echo "branches_matched=false" >> $GITHUB_ENV
        fi

    - name: Validate PR name
      if: env.branches_matched == 'true'
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ ! "$PR_TITLE" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: PR title does not match the required pattern."
          exit 1
        else
          echo "PR title is valid."
        fi

  create_release:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        ref: release

    - name: Extract PR title and check tag format
      id: extract_pr_title
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ "$PR_TITLE" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "PR_TAG=${PR_TITLE}" >> $GITHUB_ENV
        else
          echo "Error: PR title does not match the required pattern."
          exit 1
        fi

    - name: Generate Release Notes
      id: generate_release_notes
      run: |
        echo "Generating release notes for version ${{ env.PR_TAG }}" > release_notes.md
        echo "" >> release_notes.md
        echo "## Changes" >> release_notes.md
        echo "- Include any notable changes here." >> release_notes.md

    - name: Prepare release files
      run: |
        mkdir -p release_files
        cp -r elvui_clock/ElvUI_Clock/* release_files/

    - name: Create zip file
      run: |
        cd release_files
        zip -r ../ElvUI_Clock_${{ env.PR_TAG }}.zip .

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.PR_TAG }}
        release_name: ${{ env.PR_TAG }}
        draft: true
        commitish: release
        body_path: ./release_notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ElvUI_Clock_${{ env.PR_TAG }}.zip
        asset_name: ElvUI_Clock_${{ env.PR_TAG }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
